"""Инициализация пакета services."""
from app.services.generation_service import (
    MODEL_REGISTRY,
    GENERATION_MODELS,
    GENERATION_TYPES,
    PROVIDERS,
    GenerationModel,
    GenerationSetting,
    GenerationService,
    SettingOption,
    build_payload,
    get_default_settings,
    get_generation_model,
    infer_generation_type_from_endpoint,
    list_generation_types,
    list_models_by_provider,
    list_models_by_type,
    list_models_by_type_and_provider,
    list_generation_models,
    list_providers,
    validate_model_settings,
    build_model_registry,
)
from app.services.telegram_files import TelegramFilesService
from app.services.wavespeed import (
    WavespeedResult,
    WavespeedService,
    WavespeedSubmitResult,
    extract_error_message,
    extract_output_urls,
    extract_prediction_id,
    normalize_status,
)

__all__ = [
    "WavespeedService",
    "WavespeedSubmitResult",
    "WavespeedResult",
    "extract_prediction_id",
    "normalize_status",
    "extract_output_urls",
    "extract_error_message",
    "TelegramFilesService",
    "SettingOption",
    "GenerationSetting",
    "GenerationModel",
    "GenerationService",
    "MODEL_REGISTRY",
    "GENERATION_MODELS",
    "GENERATION_TYPES",
    "PROVIDERS",
    "get_generation_model",
    "infer_generation_type_from_endpoint",
    "list_generation_models",
    "list_generation_types",
    "list_providers",
    "list_models_by_type",
    "list_models_by_provider",
    "list_models_by_type_and_provider",
    "get_default_settings",
    "validate_model_settings",
    "build_payload",
    "build_model_registry",
]
