"""Инициализация пакета services."""
from app.services.generation_service import (
    MODEL_REGISTRY,
    GENERATION_MODELS,
    GENERATION_TYPES,
    PROVIDERS,
    GenerationModel,
    GenerationSetting,
    GenerationService,
    SettingOption,
    build_payload,
    get_default_settings,
    get_generation_model,
    get_required_input_type,
    infer_generation_type_from_endpoint,
    list_generation_types,
    list_models_by_provider,
    list_models_by_type,
    list_models_by_type_and_provider,
    list_generation_models,
    list_providers,
    model_requires_image,
    model_requires_media,
    model_requires_video,
    validate_model_settings,
    build_model_registry,
)
from app.services.telegram_files import TelegramFilesService
from app.services.download_links import DownloadLinkService
from app.services.crypto_payments import CryptoInvoice, CryptoPaymentProvider, CryptoPaymentStatus, StubCryptoPaymentProvider
from app.services.nowpayments import NowPaymentsService
from app.services.payments import ALLOWED_STARS_AMOUNTS, PaymentOrderNotFoundError, PaymentService
from app.services.r2_storage import R2StorageService
from app.services.wavespeed import (
    WavespeedResult,
    WavespeedService,
    WavespeedSubmitResult,
    extract_error_message,
    extract_output_urls,
    extract_prediction_id,
    normalize_status,
)

__all__ = [
    "WavespeedService",
    "WavespeedSubmitResult",
    "WavespeedResult",
    "extract_prediction_id",
    "normalize_status",
    "extract_output_urls",
    "extract_error_message",
    "TelegramFilesService",
    "DownloadLinkService",
    "CryptoInvoice",
    "CryptoPaymentProvider",
    "CryptoPaymentStatus",
    "StubCryptoPaymentProvider",
    "NowPaymentsService",
    "PaymentService",
    "PaymentOrderNotFoundError",
    "ALLOWED_STARS_AMOUNTS",
    "R2StorageService",
    "SettingOption",
    "GenerationSetting",
    "GenerationModel",
    "GenerationService",
    "MODEL_REGISTRY",
    "GENERATION_MODELS",
    "GENERATION_TYPES",
    "PROVIDERS",
    "get_generation_model",
    "get_required_input_type",
    "infer_generation_type_from_endpoint",
    "list_generation_models",
    "list_generation_types",
    "list_providers",
    "list_models_by_type",
    "list_models_by_provider",
    "list_models_by_type_and_provider",
    "model_requires_image",
    "model_requires_media",
    "model_requires_video",
    "get_default_settings",
    "validate_model_settings",
    "build_payload",
    "build_model_registry",
]
